apiVersion: v1
kind: ResourceQuota
metadata:
  name: alpha-quota
  namespace: tenant-alpha
spec:
  hard:
    requests.cpu: "1"
    limits.cpu: "1"
    requests.memory: 512Mi
    limits.memory: 512Mi
    pods: "3"
