apiVersion: v1
kind: ResourceQuota
metadata:
  name: alpha-quota
  namespace: tenant-alpha
spec:
  hard:
    requests.cpu: "4"
    limits.cpu: "4"
    requests.memory: 4Gi
    limits.memory: 4Gi
    pods: "5"
