apiVersion: v1
kind: ResourceQuota
metadata:
  name: beta-quota
  namespace: tenant-beta
spec:
  hard:
    requests.cpu: "2"
    limits.cpu: "2"
    requests.memory: 1Gi
    limits.memory: 1Gi
    pods: "5"
